/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Driver;

import GuiCovidTesting.ChartCovidTesting;
import GuiLockDown.ChartLockDown;
import GuiQuarantine.ChartGuiQuarantine;
import GuiNoMeasure.ChartGuiNoMeasure;
import GuiRegularVaccinationWithMask.ChartVaccinationWithMask;
import GuiRegularWithMask.ChartRegularWithMask;
import GuiSocialDistance.ChartSocialDistance;
import GuiSocialDistanceWithQuarantine.ChartGuiSocialDistanceWithQuarantine;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.stage.Stage;

/**
 *  This will be the driver for the project
 * @author varad
 */
public class DriverJFrame extends javax.swing.JFrame {
    private static volatile boolean javaFxLaunched = false;

    /**
     * Creates new form DriverJFrame
     */
    public DriverJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nothingJButton = new javax.swing.JButton();
        lockDownjButton = new javax.swing.JButton();
        quarantingJButton = new javax.swing.JButton();
        testingJButton = new javax.swing.JButton();
        vaccinationWithMaskJButton = new javax.swing.JButton();
        maskJButton = new javax.swing.JButton();
        socialDistanceJButton = new javax.swing.JButton();
        socialDistanceWithQuarantineJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        stopJButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nothingJButton.setText("No Measures");
        nothingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nothingJButtonActionPerformed(evt);
            }
        });

        lockDownjButton.setText("Lock Down");
        lockDownjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockDownjButtonActionPerformed(evt);
            }
        });

        quarantingJButton.setText("Quarantine");
        quarantingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quarantingJButtonActionPerformed(evt);
            }
        });

        testingJButton.setText("Testing");
        testingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testingJButtonActionPerformed(evt);
            }
        });

        vaccinationWithMaskJButton.setText("Vaccination with mask");
        vaccinationWithMaskJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccinationWithMaskJButtonActionPerformed(evt);
            }
        });

        maskJButton.setText("Mask");
        maskJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maskJButtonActionPerformed(evt);
            }
        });

        socialDistanceJButton.setText("Social Distance");
        socialDistanceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialDistanceJButtonActionPerformed(evt);
            }
        });

        socialDistanceWithQuarantineJButton.setText("Social Distance with Quarantine");
        socialDistanceWithQuarantineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialDistanceWithQuarantineJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Effects of following actions on Spread of Corona Virus");

        stopJButton1.setText("Stop");
        stopJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(socialDistanceWithQuarantineJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(socialDistanceJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vaccinationWithMaskJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(testingJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quarantingJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lockDownjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nothingJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maskJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(162, 162, 162))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stopJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lockDownjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quarantingJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(testingJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maskJButton)
                .addGap(11, 11, 11)
                .addComponent(vaccinationWithMaskJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(socialDistanceJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(socialDistanceWithQuarantineJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nothingJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stopJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lockDownjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockDownjButtonActionPerformed
        if (!javaFxLaunched) { // First time
            Platform.setImplicitExit(false);
            new Thread(()->Application.launch(ChartLockDown.class)).start();
            javaFxLaunched = true;
        } else { // Next times
            Platform.runLater(()->{
                try {
                    Application application = ChartLockDown.class.newInstance();
                    Stage primaryStage = new Stage ();
                    application.start(primaryStage);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }
        GuiLockDown.GUI.demo();

    }//GEN-LAST:event_lockDownjButtonActionPerformed

    private void quarantingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quarantingJButtonActionPerformed
        if (!javaFxLaunched) { // First time
            Platform.setImplicitExit(false);
            new Thread(()->Application.launch(ChartGuiQuarantine.class)).start();
            javaFxLaunched = true;
        } else { // Next times
            Platform.runLater(()->{
                try {
                    Application application = ChartGuiQuarantine.class.newInstance();
                    Stage primaryStage = new Stage ();
                    application.start(primaryStage);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }
        GuiQuarantine.GUI.demo();
    }//GEN-LAST:event_quarantingJButtonActionPerformed

    private void testingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testingJButtonActionPerformed
        if (!javaFxLaunched) { // First time
            Platform.setImplicitExit(false);
            new Thread(()->Application.launch(ChartCovidTesting.class)).start();
            javaFxLaunched = true;
        } else { // Next times
            Platform.runLater(()->{
                try {
                    Application application = ChartCovidTesting.class.newInstance();
                    Stage primaryStage = new Stage ();
                    application.start(primaryStage);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }
        GuiCovidTesting.GUI.demo();

    }//GEN-LAST:event_testingJButtonActionPerformed

    private void maskJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maskJButtonActionPerformed
        if (!javaFxLaunched) { // First time
            Platform.setImplicitExit(false);
            new Thread(()->Application.launch(ChartRegularWithMask.class)).start();
            javaFxLaunched = true;
        } else { // Next times
            Platform.runLater(()->{
                try {
                    Application application = ChartRegularWithMask.class.newInstance();
                    Stage primaryStage = new Stage ();
                    application.start(primaryStage);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }
        GuiRegularWithMask.GUI.demo();
    }//GEN-LAST:event_maskJButtonActionPerformed

    private void vaccinationWithMaskJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccinationWithMaskJButtonActionPerformed

        if (!javaFxLaunched) { // First time
            Platform.setImplicitExit(false);
            new Thread(()->Application.launch(ChartVaccinationWithMask.class)).start();
            javaFxLaunched = true;
        } else { // Next times
            Platform.runLater(()->{
                try {
                    Application application = ChartVaccinationWithMask.class.newInstance();
                    Stage primaryStage = new Stage ();
                    application.start(primaryStage);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }
        GuiRegularVaccinationWithMask.GUI.demo();
    }//GEN-LAST:event_vaccinationWithMaskJButtonActionPerformed

    private void socialDistanceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialDistanceJButtonActionPerformed

        if (!javaFxLaunched) { // First time
            Platform.setImplicitExit(false);
            new Thread(()->Application.launch(ChartSocialDistance.class)).start();
            javaFxLaunched = true;
        } else { // Next times
            Platform.runLater(()->{
                try {
                    Application application = ChartSocialDistance.class.newInstance();
                    Stage primaryStage = new Stage ();
                    application.start(primaryStage);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }
        GuiSocialDistance.GUI.demo();
    }//GEN-LAST:event_socialDistanceJButtonActionPerformed

    private void socialDistanceWithQuarantineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialDistanceWithQuarantineJButtonActionPerformed

        if (!javaFxLaunched) { // First time
            Platform.setImplicitExit(false);
            new Thread(()->Application.launch(ChartGuiSocialDistanceWithQuarantine.class)).start();
            javaFxLaunched = true;
        } else { // Next times
            Platform.runLater(()->{
                try {
                    Application application = ChartGuiSocialDistanceWithQuarantine.class.newInstance();
                    Stage primaryStage = new Stage ();
                    application.start(primaryStage);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }
        GuiSocialDistanceWithQuarantine.GUI.demo();
    }//GEN-LAST:event_socialDistanceWithQuarantineJButtonActionPerformed

    private void nothingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nothingJButtonActionPerformed


        if (!javaFxLaunched) { // First time
            Platform.setImplicitExit(false);
            new Thread(()->Application.launch(ChartGuiNoMeasure.class)).start();
            javaFxLaunched = true;
        } else { // Next times
            Platform.runLater(()->{
                try {
                    Application application = ChartGuiNoMeasure.class.newInstance();
                    Stage primaryStage = new Stage ();
                    application.start(primaryStage);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }
        GuiNoMeasure.GUI.demo();
    }//GEN-LAST:event_nothingJButtonActionPerformed

    private void stopJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopJButton1ActionPerformed

        dispose();
        String[] args = {""};
        Driver.DriverJFrame.main(args);
    }//GEN-LAST:event_stopJButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lockDownjButton;
    private javax.swing.JButton maskJButton;
    private javax.swing.JButton nothingJButton;
    private javax.swing.JButton quarantingJButton;
    private javax.swing.JButton socialDistanceJButton;
    private javax.swing.JButton socialDistanceWithQuarantineJButton;
    private javax.swing.JButton stopJButton1;
    private javax.swing.JButton testingJButton;
    private javax.swing.JButton vaccinationWithMaskJButton;
    // End of variables declaration//GEN-END:variables
}
